# Define the platform flags expected by the dependency wrappers without
# retaining the retired downloaded-prebuilt path layout.
if(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(WINDOWS TRUE)
    set(SYSTEM_STRING "Windows Desktop")
elseif(ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
    set(SYSTEM_STRING "Android")
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(LINUX TRUE)
    set(SYSTEM_STRING "Linux")
elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(APPLE TRUE)
    if(IOS)
        set(SYSTEM_STRING "iOS")
    else()
        set(MACOSX TRUE)
        set(SYSTEM_STRING "macOS")
    endif()
endif()
