# Build the official Independent JPEG Group source locally. Keep the vendored
# source pristine: jconfig.h is generated in the CMake binary tree.
set(jpeg_source_dir "${COCOS_EXTERNAL_ROOT}/jpeg")
set(jpeg_binary_dir "${CMAKE_CURRENT_BINARY_DIR}/jpeg")

file(MAKE_DIRECTORY "${jpeg_binary_dir}")
file(WRITE "${jpeg_binary_dir}/jconfig.h" [=[/* Generated by external/cmake/jpeg.cmake. */
#ifndef JCONFIG_H
#define JCONFIG_H

#define HAVE_PROTOTYPES 1
#define HAVE_UNSIGNED_CHAR 1
#define HAVE_UNSIGNED_SHORT 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_LOCALE_H 1

#if defined(_WIN32) && !defined(__RPCNDR_H__)
typedef unsigned char boolean;
#define HAVE_BOOLEAN 1
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif
#endif

#ifdef JPEG_INTERNALS
#define INLINE inline
#endif
#endif
]=])

set(jpeg_sources
    jaricom.c jcapimin.c jcapistd.c jcarith.c jccoefct.c jccolor.c
    jcdctmgr.c jchuff.c jcinit.c jcmainct.c jcmarker.c jcmaster.c
    jcomapi.c jcparam.c jcprepct.c jcsample.c jctrans.c jdapimin.c
    jdapistd.c jdarith.c jdatadst.c jdatasrc.c jdcoefct.c jdcolor.c
    jddctmgr.c jdhuff.c jdinput.c jdmainct.c jdmarker.c jdmaster.c
    jdmerge.c jdpostct.c jdsample.c jdtrans.c jerror.c jfdctflt.c
    jfdctfst.c jfdctint.c jidctflt.c jidctfst.c jidctint.c jquant1.c
    jquant2.c jutils.c jmemmgr.c jmemnobs.c
)
list(TRANSFORM jpeg_sources PREPEND "${jpeg_source_dir}/")

add_library(jpeg STATIC ${jpeg_sources})
target_include_directories(jpeg
    PUBLIC
        "${jpeg_source_dir}"
        "${jpeg_binary_dir}"
)
set_target_properties(jpeg PROPERTIES FOLDER "External")
add_library(ext_jpeg ALIAS jpeg)

unset(jpeg_binary_dir)
unset(jpeg_source_dir)
unset(jpeg_sources)
